#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X 

bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
/usr/bin/feh --bg-fill /home/sergio/Documents/fondos/fondo.jpg
bspc config focused_border_color "#84c0fc"
bspc config border_width 3
bspc config border_radius 0
bash ~/.config/polybar/launch.sh --forest
bspc config top_padding 35
#xrandr --output eDP-1 --off
#xrandr --output eDP-1 --mode 1920x1200 --rate 120
#xrandr --output DP-1 --mode 1920x1080 --rate 60
#xrandr --output HDMI-1 --mode 2560x1440 --rate 60
#xrandr --output HDMI-1 --primary
#xrandr --output HDMI-1 --mode 2560x1440 --rate 60 
picom &
